[package]
name = "exhume_indexer"
version = "0.2.0"
edition = "2021"
description = "Filesystem indexing and artefact extraction for Exhume."
repository = "https://github.com/forensicxlab/exhume"
documentation = "https://www.forensicxlab.com/docs/category/exhume---indexer"
readme = "README.md"
authors = ["k1nd0ne"]
license = "GPL-2.0-or-later"
keywords = ["forensics", "dfir", "indexer", "sqlite", "exhume"]

[dependencies]
exhume_body = "=0.5.5"
exhume_filesystem = "=0.5.2"
exhume_artefacts = { version = "=0.3.0", path = "../exhume_artefacts" }

tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio-rustls", "json"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
hex = "0.4"
file_type = "0.8.8"
indicatif = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
regex = "1.10.5"
anyhow = "1"
clap = { version = "4.5", features = ["cargo"] }
clap-num = "1.1.1"
